language: python

python:
  - "3.8"

services: postgresql

addons:
  postgresql: "9.6"

env:
  - DJANGO=3.1

before_install:
  - export DJANGO_SETTINGS_MODULE=conf.settings
  - export PYTHONPATH=$HOME/builds/zachang/pizzaspot
  - export PIP_USE_MIRRORS=true

# install requirements
install:
  - pip install pipenv
  - make pip-install
  - pipenv install django==$DJANGO
  - pipenv install psycopg2

before_script:
  - psql -c "CREATE DATABASE pizzaspot;" -U postgres
  - make migrations
  - make migrate

# command to run tests
script:
  - python manage.py collectstatic --noinput --settings=conf.settings
  - make test_coverage

# send coverage report to coveralls
after_success:
  coveralls