# Generated by Django 3.1.2 on 2020-11-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavors', models.CharField(choices=[('margarita', 'Margarita'), ('marinara', 'Marinara'), ('salami', 'Salami')], default='salami', max_length=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.CharField(choices=[('lg', 'Large'), ('md', 'Medium'), ('sm', 'Small')], default='sm', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('toppings', models.ManyToManyField(related_name='pizzas', to='pizza.Topping')),
            ],
            options={
                'unique_together': {('flavors', 'size')},
            },
        ),
    ]
