# Generated by Django 3.1.2 on 2020-11-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='flavors',
            new_name='flavor',
        ),
        migrations.AlterUniqueTogether(
            name='pizza',
            unique_together={('flavor', 'size')},
        ),
    ]
