# Generated by Django 3.1.2 on 2020-11-01 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza', '0002_auto_20201101_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cancel_reason', models.TextField(null=True)),
                ('checkout_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.TextField()),
                ('delivery_status', models.CharField(choices=[('cancelled', 'cancelled'), ('delivering', 'delivering'), ('delivered', 'delivered'), ('processing', 'processing'), ('ready', 'ready')], default='processing', max_length=10)),
                ('phone_number', models.CharField(max_length=14)),
                ('tracking_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_status', models.CharField(choices=[('delivered', 'delivered'), ('undelivered', 'undelivered')], default='undelivered', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='order.order')),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='pizza.pizza')),
            ],
        ),
    ]
