# Generated by Django 3.1.2 on 2020-11-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201101_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tracking_number',
            new_name='id',
        ),
    ]
