# Generated by Django 3.1.2 on 2020-11-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201102_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('delivering', 'delivering'), ('delivered', 'delivered'), ('pending', 'no checkout'), ('preparing', 'preparing'), ('ready', 'ready')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('undelivered', 'undelivered')], default='undelivered', max_length=11),
        ),
    ]
