# Generated by Django 3.1.2 on 2020-11-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20201101_1357'),
        ('order', '0014_auto_20201102_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order_items', to='pizza.pizza'),
        ),
    ]
