# Generated by Django 3.1.2 on 2020-11-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20201101_1357'),
        ('order', '0016_auto_20201102_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order_items', to='pizza.pizza'),
            preserve_default=False,
        ),
    ]
