# Generated by Django 3.1.2 on 2020-11-02 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20201102_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_status',
        ),
    ]
